### ISSUE TITLE
DirectX 11 Issues with the koikatsu.yml

### ISSUE THREAD

**Issue by ghost** [CPU-Blanc/Lutris-Scripts#1]
Hello there, i'm using Arch Linux with KDE Plasma Wayland and  I can''t seem to get the game running. Whenever i try to launch the game, i get an error window with the following text : 
![image](https://user-images.githubusercontent.com/75695425/194159739-8b72c186-3e20-42a6-a2a9-f357e467e4f8.png)

**Comment by CPU-Blanc** [comment]
Sorry for the delay!

Huh, very odd. What graphics card are you running?
Make sure you've got all the correct drivers and 32-bit packages installed too

**Comment by ghost** [comment]
I have HD Graphics 520 and a Radeon R5 m330, 32 bit packages are installed
i think.

**Comment by CPU-Blanc** [comment]
It _might_ be that for some reason your laptop is defaulting to using the Intel integrated graphics rather than your Radeon, which would explain why it cannot initialise DX11.

There's a couple of ways we could try and test/verify this.
Firstly you can go into your lutris preferences -> Global Options and ensure `Use discrete GPU` is checked. Try this first.

You might also be able to test this by running lutris with `DRI_PRIME` from your terminal:
`DRI_PRIME=1 lutris`

**Comment by CPU-Blanc** [comment]
Gonna close this for now, as it seems to be more of an issue with Linux graphics drivers and not properly switching between integrated and dedicated graphics, rather than the script itself. Feel free to reopen this if you're having issues still.
